spring:
  application:
    name: powerplan

  supabase:
    url: ${POWERPLAN_SUPABASE_URL}
    key: ${POWERPLAN_SUPABASE_ANON_KEY}
    schema: public

springdoc:
  swagger-ui:
    operations-sorter: alpha
